#!/bin/csh

#BSUB -L /bin/csh
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -B
#BSUB -N
#BSUB -u pmung@umich.edu
#BSUB -J JBNAME

#BSUB -P acc_schlea02a 
#BSUB -q premium	# alloc / premium (1.5x)/ expressalloc (2h max)/ low
#BSUB -m manda         # New Intel (mothra), 2.5x SU; Legacy AMD (manda) 
#BSUB -W 6:00          # Wall clock limit for job
#BSUB -n 12              # Number of CPU cores required
#BSUB -R "span[ptile=12]"        # Run [ptile] number of MPI task per node

## For Minerva Cluster Use

module load schrodinger/2015-2

# set shell variables (job name, running, working directories, etc)
set userdir = "/hpc/users/ungp01"
set homedir = $userdir/0_ligprep
set workdir = /sc/orga/scratch/ungp01/0_ligprep
set ligdir  = '\/sc\/orga\/projects\/schlea02a\/8_lib\/zinc_frag15\/src'	# need \
set localdr = JBNAME

# Set schrodinger.hosts parameters
set schdir  = "/hpc/users/ungp01/.schrodinger"
set schwork = '/sc/orga/scratch/ungp01/0_ligprep'
set schtmp  = '\/sc\/orga\/scratch\/ungp01\/0_ligprep'	# need \
set schhome = '\/hpc\/packages\/minerva-common\/schrodinger\/2015-2' # need \

set schhost = premium	# alloc / premium (1.5x) / expressalloc (2h max)
set schacct = acc_schlea02a
set scharch = manda	# Intel (mothra) 2.5x SU / Legacy AMD (manda)
set schtime = 6:00	# Wall clock limit for job (hour)
set schcpu  = 12	# CPU core required
set schcore = 12	# CPU core in MPI per node
set schnjob = 24	# split job into subjobs

##########################################################################
#Set procedure to run
cd $workdir
mkdir $localdr
cd $localdr
echo `pwd`

# ESSENTIAL. Change schrodinger.hosts file parameters
$schdir/make_Sch_host.csh $schhost $schacct $scharch $schcpu \
          $schcore $schtime $schhome $schtmp

##########################################################################

# Change schrodinger job input file ligand directory
#sed "s/XDIRECTORY/$ligdir/" $homedir/INP > ./INP

# Run Schrodinger job
#
# ## Generate single, most probable tautomer in 3D per ligand, instead of
# ## multiple tautomer per ligand; result is comparable to OMEGA2 at pH=7.0
#time ${SCHRODINGER}/ligprep -WAIT \
#        -inp INP \
#        -HOST localhost:$schcpu \
#        -NJOBS 24 

## Run Schrodinger job
## since 2015.03, the flag '-r 1' is depricated.
#time ${SCHRODINGER}/ligprep -WAIT -LOCAL \
#        -i 2   -epik -We,-ph,7.2,-pht,0.3,-ms,1 \
#        -s 1 -t 1 \
#        -bff   16 \
#        -ismi  $homedir/SDIN.smi \
#        -osd   SDIN.sdf.gz \
#        -HOST  localhost:$schcpu \
#        -NJOBS $schnjob

echo $!

## PAINS filter
  $SCHRODINGER/utilities/canvasSearch -WAIT \
        -isd   SDIN.sdf.gz \
        -osd   SDIN.sch.sdf.gz \
        -osd2  SDIN.fail.sdf.gz -filter  \
        -file  $homedir/all-1.sch.pains_filter.cflt \
        -JOB   JBNAME \
        -HOST  localhost:$schcpu


@ i = 1
while ($i >= 1)
  echo check-time $i `date`
  if (! -e LIGNAME.sch.sdf ) then 
    @ i++
    sleep 3m
  else
    @ i = 0
    sleep 5m
    gzip LIGNAME.sch.sdf
    echo finished, bkill JBNAME `date`
    bkill -J JBNAME
    echo pass bkill `date`
    exit
    echo exit `date`
  endif
end

exit

