#!/bin/csh

#BSUB -L /bin/csh
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -B
#BSUB -N
#BSUB -u pmung@umich.edu
#BSUB -J JBNAME

#BSUB -P acc_schlea02a 
#BSUB -q premium	# alloc / premium (1.5x)/ expressalloc (2h max)/ low
#BSUB -W 48:00          # Wall clock limit for job
#BSUB -n 8              # Number of CPU cores required
#BSUB -R "span[ptile=8]"        # Run [ptile] number of MPI task per node

## For Minerva Cluster Use

##########################################################################
# set shell variables (job name, running, working directories, etc)
set homedir = "/hpc/users/ungp01/0_ligprep"
set workdir = /sc/hydra/scratch/ungp01/0_ligprep
set smi_dir = /sc/hydra/projects/schlea02a/8_lib/zld19
#set ligdir  = '\/sc\/hydra\/projects\/schlea02a\/8_lib\/zinc_frag15\/glide'	# need \
set localdr = JBNAME

set cpu     = 8
set confgen = 300

##########################################################################
#Set procedure to run
if (! -e $workdir) then
  mkdir $workdir
endif
cd $workdir
mkdir $localdr
cd $localdr
echo `pwd`

##########################################################################

setenv OE_DIR /sc/hydra/projects/schlea02a/8_lib/openeye
setenv OE_LICENSE $OE_DIR/oe_license.txt
setenv OE_ARCH redhat-RHEL7-x64

set input  = $smi_dir/SDFILE
set output = SDIN.oeb.gz

omega2 \
  -mpi_np   $cpu      \
  -in       $input    \
  -out      $output   \
  -prefix   SDIN      \
  -maxconfs $confgen  \
  -progress none      \
  -strict   false

exit

